-- File: mux.vhd
-- Generated by MyHDL 0.6
-- Date: Sat Apr 30 03:26:39 2011

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_06.all;

entity mux is
    port (
        s: in unsigned(0 downto 0);
        o: out unsigned(31 downto 0);
        a: in unsigned(31 downto 0);
        b: in unsigned(31 downto 0)
    );
end entity mux;

architecture MyHDL of mux is


begin


MUX_LOGIC: process (a, s, b) is
begin
    if (s = 0) then
        o <= a;
    else
        o <= b;
    end if;
end process MUX_LOGIC;

end architecture MyHDL;
